env:
  global:
  - secure: AeF67FRnEFRNX8XyfrGuvDoMJBuVmBKLVxePKmBy07FZYGiWmSmPWwFScy8Z6+RmwlwuGXwH2tlKmMYQj6Qtb+mWz+mBv74gOPQ4DemFvd2p7sdOhN2n4FUeaXp3X0s2a2xM09nyaFottoHVfZA2wVne1Ba34VYjfAkSIruyM4NZyybUhtNWBLvIrSxR24PLVQ1tv8GBOL/07ZAVzY4QDTC6azL5sufQtyetZ/xneTzQXa2nl+jeQonRh0Kczb1yjXcSqoqdyEPaLtXkYjbmaU+Bh1xjTg9Qjr2c6NtpxxMk9u/rEaQvOf2Q9RGA3kmyrPv1UKLiMnh+NnncQPRU3EA4Afd7Y0hRXa3hlf3d6h1zO7VrH00MwR7qve4f2R9B4Nh22HjaWdIfh2Pl065gkWvUuf4EbviFKELo5rG7MIS/lPDK86EasUlFQ8kB39yypeSgNG5oT0h1NgLSs+qUFxZMlmPSJsoqUacajEXnRnz75EMYyYMvcp+QGql+FhK5A3N0Oehi35oaVgKC4ZjTJKhYzhqAQeWYkZrMnOcPyKKlmJbPqNqsTy5X1yn079TanjDar4ZzAneCRlxyNC9Cp5oZ3K1WkBKg4JRyWZat+0LrZvP8hvfzbDrShwoDS7fyXCfyfT31zCnUDuCD45IL4iICasJ8rLi9GZinixlxj7I=
  - secure: VXj164pnZeUDv46HkkuCNA3ZqhnhdHdiS5kR9X1cdFsRUSSmMAMZWL5jmfg4QWUSrGvYFuyoNQtVNNNY7q6Wdu+aABTg0/5nkSteMsASQPyCLTGLYphQ+XSz1wwGHd94wYWAx6SOClQk+X8JOz5DmF6T+fW4AMQ9yCQQx1JDc/2dPsTcGpVT3YP2gROy4Fu8gOIeSd2E43ZeFb3pE0iYcILJvAd/5roTu7DELmBr2SBXuB2jh/ttvCVQpKw6m2h/B8qDogSTQ/cZvjoaxMIXwoA6oSmnamXu7NUYaJ9tJOJ1NqA5Yr5HubPMsYA1putzFN5ueW7RSU2lJeGY531noF2ylZ0mvlfERgKx8PwYqweNEkGvjWK801ZPo49mxCpNjnv3g6gG8PMs8EBVD0DBi1I4Gkzrqo2E5nFkwKHp5dsIlwwGHBOzXp0eCafJtOyRE2ikD8iqf64SM+wTd7mlx+8eYKs7jmd66spuNAxEJQcMl8/a+gwFiHrEh5o2y3R6iq9luN1XTT/g48vl+U5/ImhjjpvA4pMXTQ8867DL81bOa3Xren+2S8JD/4QNzUQ1zgDLg9peHcdsOekYPIEgaxb9JkODe+PklcvEQv2KcNBrUMNbXEEOJW9b4eFLXcvB/MjSVLYvOgbpU/6Mlgo1wjFIwTTEZ57R2uLWyRTdiXQ=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: g3c47n3T4TNQcU5lbY/h3/kbsYzqLsyPMPFboPAhZXErBPvgJaErfZ4uY0nhMP5shaMKjNo7wfbWFdm3giTljtsuNnxBBr/nfEOhmYVQvG1+YYXRdaxrZg+cU7K1lA1IQXfgJO83NSVinCy3aCE1ZhCzoN/P86qYtpEYPLYVKVIu3vRufG+6P+au4wJ1+GGb0D1deQTHhEHZIqFcsLou+OH2aC1Vm7ram7xy63PLIu8/llP4wG4d2aE41jVPMc9aRRSsHSN3gC+Vngne0Z0zYYBEXaYhmr7zTl0tx+1NkoM9KP2fKZo0SLkywqDEXCtCT4TINRea3B3/MDcAMnIVVAMYjbmYLeugQUUszmgf+ASsTpGHie/ZoGACGQl4Uu0FU3ltXB9dJKxAqBTUZi9EdoTA2CABYkzv0VRcdfmlW0OcaVoaNNoYkSYJPvzgy34CPH1tNU8Zj2YlwEubY15fgiV/2Sia3NzXMf5/1g9oKViuLUj7KAHS50AE9QAaP5Gzu224OQHQ5w2pDM5WPozDPNRhlulefsytcx0mnTxXAdqs/z62NfGPSavS0GzvvfaeNlXLDXFlzHzgik7mGV6c6KjzmpyPZ7zhr0n8vp5SdpRRLzGA3zkAFdZRwgsGPyKqBlHSDoMd7W8bHGeMAQ/sEf6BLUh7Xbwb9LGEoD6E804=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull asfram/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t asfram/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: jjzSS8sBdrY13GlEKwZOerbwhVba8MdsDOk6NqsxTbJd0Ygg4WFhrXquxioU+wf++Fafmn41lAwmdZ0pvblIoGwpffC56ry4CE+xb6W4wK4NCYrhnHTFGRjRdfbev7ddkSuoAJ1dCleMLBzNhFls6/Gojy77aHULhsQHSQ4Ebb+JvrBQjodQzABKpxzsNqpWksWxv3SoZ7aAgjc8aDEixrHipSiUjR+HSgs/qlP2o9qj0zNcYhuSbdMw20LQ5ynr01jccDEl029mJW74AXSGZAaIDWmXXbq/w0gBW1eJ94lzcXgli6Gw30okPR/UHD28dKAR5AQ/dIbSCmH3lHt1Akhuau5Katu0NoMMndsDMNnXS3dHgwJul9L3FdZOo0TII4uITNOvXGZgAgGAdj8vq69GjbPfcMyKMWHDV6mSmFeUm4+7JYvCB7of4DicvstVDs7I1cbV5xsDZy1JgDjsZ6cojYvgNO+LWtdhz54ucaQ2v+lC6if8tVIkSwMpIbTQmFbCuGZgo5na37+ko4iUc/MY0m7WEpx3NEtBcFc3N/lK3mhI52i1oDEBkXLU23/2AYuf8qzbye9BUcB30QLQFP7frtPSKn34DC2QbDMCbmZD0uiR4PMthQC+YTgfD69rNqKXxxR7cEbXuzCSFa+/oP72zs98keNJSUC/KxpFwQA=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
